### ISSUE TITLE
test-mast fails with 3 errors

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#56]
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_

_Please answer each question as best as you can_

1. **What were you trying to do?** execute test-mast to verify a new install of mast works
2. **What were you expecting to happen?** all tests to run and pass
3. **What were the actual results?** 3 errors
4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?** fresh install that was updated after downloading a fresh copy of build-hotfix from github
5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).**

>test-mast.bat -A
0.125: test_mast_imports.TestMASTImports.test_import_cherrypy
0.000: test_mast_imports.TestMASTImports.test_import_commandr
0.016: test_mast_imports.TestMASTImports.test_import_dulwich
0.000: test_mast_imports.TestMASTImports.test_import_ecdsa
0.000: test_mast_imports.TestMASTImports.test_import_markdown
0.000: test_mast_imports.TestMASTImports.test_import_mast_cli
0.000: test_mast_imports.TestMASTImports.test_import_mast_config
0.000: test_mast_imports.TestMASTImports.test_import_mast_cron
0.578: test_mast_imports.TestMASTImports.test_import_mast_daemon
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_accounts
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_backups
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_crypto
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_datapower
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_deploy
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_deployment
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_developer
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_network
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_ssh
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_status
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_system
0.000: test_mast_imports.TestMASTImports.test_import_mast_datapower_web
0.000: test_mast_imports.TestMASTImports.test_import_mast_hashes
0.000: test_mast_imports.TestMASTImports.test_import_mast_logging
0.000: test_mast_imports.TestMASTImports.test_import_mast_plugin_utils
0.000: test_mast_imports.TestMASTImports.test_import_mast_plugins
0.000: test_mast_imports.TestMASTImports.test_import_mast_pprint
0.000: test_mast_imports.TestMASTImports.test_import_mast_test
0.000: test_mast_imports.TestMASTImports.test_import_mast_timestamp
0.000: test_mast_imports.TestMASTImports.test_import_mast_xor
0.000: test_mast_imports.TestMASTImports.test_import_paramiko
======================================================================
ERROR: test_mast_datapower_system (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_mast_datapower_system
Traceback (most recent call last):
  File "D:\tools\mast\2.1\anaconda\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "D:\tools\mast\2.1\anaconda\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\tools\mast\2.1\anaconda\lib\site-packages\mast.testsuite-2.1.0-py2.7.egg\mast\testsuite\unit\test_mast_datapower_system.py", line 7, in <module>
    import mock
ImportError: No module named mock

======================================================================
ERROR: test_import_paramiko (test_mast_imports.TestMASTImports)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\tools\mast\2.1\anaconda\lib\site-packages\mast.testsuite-2.1.0-py2.7.egg\mast\testsuite\unit\test_mast_imports.py", line 123, in test_import_paramiko
    import paramiko
  File "build\bdist.win-amd64\egg\paramiko\__init__.py", line 30, in <module>
  File "build\bdist.win-amd64\egg\paramiko\transport.py", line 36, in <module>
ImportError: cannot import name util

======================================================================
ERROR: test_datapower_py (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_datapower_py
Traceback (most recent call last):
  File "D:\tools\mast\2.1\anaconda\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "D:\tools\mast\2.1\anaconda\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\tools\mast\2.1\anaconda\lib\site-packages\mast.testsuite-2.1.0-py2.7.egg\mast\testsuite\regression\test_datapower_py.py", line 3, in <module>
    import mock
ImportError: No module named mock

----------------------------------------------------------------------
Ran 32 tests in 0.813s

FAILED (errors=3)

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by briankearney** [comment]
If I run build-hotfix again, since I know that multiple executions of build-hotfix may be necessary after a fresh install, it fails again, but this time with only one error:

======================================================================
ERROR: test_import_paramiko (test_mast_imports.TestMASTImports)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\tools\mast\2.1\anaconda\lib\site-packages\mast.testsuite-2.1.0-py2.7.egg\mast\testsuite\unit\test_mast_imports.py", line 123, in test_import_paramiko
    import paramiko
  File "build\bdist.win-amd64\egg\paramiko\__init__.py", line 30, in <module>
  File "build\bdist.win-amd64\egg\paramiko\transport.py", line 36, in <module>
ImportError: cannot import name util

----------------------------------------------------------------------
Ran 32 tests in 1.110s

FAILED (errors=1)

By the way, before running build-hotfix, I checked and I did get errors from mast-ssh too, like this:

>mast-ssh.bat -a hostname -c user:pass -d default
Traceback (most recent call last):
  File "D:\tools\mast\2.1\anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\tools\mast\2.1\anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win-amd64\egg\mast\datapower\ssh\__main__.py", line 177, in <module>
  File "build\bdist.win-amd64\egg\mast\cli\__init__.py", line 251, in run
  File "build\bdist.win-amd64\egg\mast\datapower\ssh\__main__.py", line 143, in main
  File "build\bdist.win-amd64\egg\mast\datapower\ssh\__main__.py", line 56, in initialize_appliances
  File "build\bdist.win-amd64\egg\mast\datapower\datapower\DataPower.py", line 148, in wrapper
  File "build\bdist.win-amd64\egg\mast\logging\__init__.py", line 278, in _wrapper
  File "build\bdist.win-amd64\egg\mast\datapower\datapower\DataPower.py", line 846, in ssh_connect
NameError: global name 'paramiko' is not defined

I am going to try a third run of build-hotfix and see if that helps...

**Comment by briankearney** [comment]
a third run of build-hotfix did not resolve the issue... 
[log.zip](https://github.com/McIndi/mast/files/452230/log.zip)

**Comment by iLoveTux** [comment]
Just a side-note, I'll be submitting a new issue to allow mast-ssh to accept a port parameter since it currently does not.

**Comment by iLoveTux** [comment]
So it appears as though there are two issues here:

1. __Unable to import mock__: This seems to have been fixed by the update
2. __Cannot import name util__: The paramiko installation seems to have been corrupted. This is the library which provides us our ssh functionality.

It seems strange as this would be the first time that this package has caused us issues, so I am more likely to suspect our build-hotfix.py script which has been known to have some issues...still, in order to fix this we need to fix the paramiko installation.

Does this machine have internet access without a firewall which would prevent `pip` or `conda` from working?

If so, we can try this:

```bash
$ conda install --force paramiko 
```
If we get this working, we can confidently move on to identifying the underlying issue.

**Comment by iLoveTux** [comment]
OK, so I need one more log file from you, this one should be in `$MAST_HOME/tmp/2016xxxxxxxxxx-hotfix-build/hotfix-2016xxxxxxxxx/install.log`

This will allow me to see what exactly happened when installing the hotfix that was built.

**Comment by briankearney** [comment]
Yes, this machine has internet access without a firewall (do you still want
me to try conda install --force paramiko?)

Log attached

**Comment by iLoveTux** [comment]
yes, I would like to get you up and running also this will serve as proof that the problem is the installation of paramiko and not something misleading.

So the conda command (in theory) should fix this issue. I will start examining the log to find out what exactly went wrong.

**Comment by iLoveTux** [comment]
I'm having trouble finding that log, could you email it to me?

**Comment by briankearney** [comment]
here


On Fri, Sep 2, 2016 at 1:09 PM, Clifford Bressette <notifications@github.com

**Comment by briankearney** [comment]
even after the conda command, it still fails:

======================================================================
ERROR: test_import_paramiko (test_mast_imports.TestMASTImports)
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"D:\tools\mast\2.1\anaconda\lib\site-packages\mast.testsuite-2.1.0-py2.7.egg\mast\testsuite\unit\test_mast_imports.py",
line 123, in test_import_paramiko
    import paramiko
  File "build\bdist.win-amd64\egg\paramiko\__init__.py", line 30, in
<module>
  File "build\bdist.win-amd64\egg\paramiko\transport.py", line 36, in
<module>
ImportError: cannot import name util

----------------------------------------------------------------------
Ran 32 tests in 2.496s

FAILED (errors=1)

**Comment by iLoveTux** [comment]
I'm closing this issue, I believe that this was solved by updating build-hotfix to the latest version before running it. if not, please re-open
